# Generated by Django 4.1.3 on 2022-11-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeBasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('years', models.IntegerField()),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeExperienceInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('exp_start', models.DateField()),
                ('exp_end', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_rating', models.CharField(max_length=15)),
                ('company_city', models.CharField(max_length=100)),
                ('company_state', models.CharField(max_length=100)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeEducationInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rank', models.CharField(max_length=200)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenceInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI_number', models.CharField(max_length=100)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_states_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('active_start', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_rating', models.CharField(max_length=15)),
                ('company_city', models.CharField(max_length=100)),
                ('company_state', models.CharField(max_length=100)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_info', to='resume_extractor.resumebasicinfomodel')),
            ],
        ),
    ]
